// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxrfhkxsukrjumpcdwlg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4cmZoa3hzdWtyanVtcGNkd2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMzc3MzksImV4cCI6MjA2OTkxMzczOX0.7MoLzCydF-GJBUyr8DKEskEWeg87pViKetEhdEhRs6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});